name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      - name: Install Backend Dependencies
        run: |
          cd jobetus/back
          npm install

      - name: Run Backend Tests
        run: |
          cd jobetus/back
          npm test
